/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vocabulary, categories and attribute schemas. The same for everyone signed in. */
        get: operations["config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthy means: the process is up AND the database answers. */
        get: operations["health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["people_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["teams_list"];
        put?: never;
        post: operations["teams_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["teams_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/members/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["teams_removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["units_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/work-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workItems_list"];
        put?: never;
        post: operations["workItems_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/work-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workItems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["workItems_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddMemberBody: {
            person_id: string;
            start_time?: string | null;
        };
        AuthConfigView: {
            /** @description The client id this publishable key signs in as. */
            client_id: string;
            /**
             * @description Rauthy's issuer, exactly as in tokens' `iss`. The SDK fetches
             *     `{issuer}.well-known/openid-configuration` for the authorization and
             *     token endpoints.
             */
            issuer: string;
        };
        CategoryView: {
            color?: string | null;
            icon?: string | null;
            id: string;
            key: string;
            label: string;
        };
        ConfigView: {
            /** @description entity → JSON Schema for its `attributes` */
            attribute_schemas: Record<string, never>;
            /** @description entity → its categories in display order */
            categories: {
                [key: string]: components["schemas"]["CategoryView"][];
            };
            /** @description key → words, e.g. "work_item" → {"singular": "Körning", "plural": "Körningar"} */
            vocabulary: {
                [key: string]: components["schemas"]["WordView"];
            };
        };
        MePerson: {
            email?: string | null;
            first_name: string;
            id: string;
            language: string;
            last_name?: string | null;
            role: string;
        };
        MeView: {
            /**
             * @description What this role may do, e.g. "work_item.write". A convenience for the
             *     frontend to show or hide controls; the api enforces these itself.
             */
            can: string[];
            person: components["schemas"]["MePerson"];
            units: components["schemas"]["UnitRef"][];
        };
        /** @description Only the fields that changed, plus the `version` that was loaded. */
        PatchBody: {
            billing_status?: string | null;
            customer_name?: string | null;
            customer_ref?: string | null;
            date?: string | null;
            description?: string | null;
            end_time?: string | null;
            /** Format: int64 */
            people_needed?: number | null;
            /** Format: int64 */
            resources_needed?: number | null;
            start_time?: string | null;
            status?: string | null;
            title?: string | null;
            /** Format: int64 */
            version: number;
        };
        PersonAdmin: {
            access_expires_at?: string | null;
            alias?: string | null;
            category_id?: string | null;
            email?: string | null;
            first_name: string;
            has_login: boolean;
            id: string;
            is_active: boolean;
            language: string;
            last_name?: string | null;
            phone?: string | null;
            role: string;
            unit_ids: string[];
            /** Format: int64 */
            version: number;
        };
        PersonCrew: {
            alias?: string | null;
            first_name: string;
            id: string;
            last_name?: string | null;
        };
        PersonStaff: {
            alias?: string | null;
            category_id?: string | null;
            email?: string | null;
            first_name: string;
            id: string;
            last_name?: string | null;
            phone?: string | null;
            role: string;
            unit_ids: string[];
        };
        PersonView: components["schemas"]["PersonAdmin"] | components["schemas"]["PersonStaff"] | components["schemas"]["PersonCrew"];
        TeamCreateBody: {
            date: string;
            leader_id?: string | null;
            name?: string | null;
            unit_id: string;
        };
        TeamMemberView: {
            meet_at?: string | null;
            person_id: string;
            start_time?: string | null;
        };
        TeamView: {
            date: string;
            id: string;
            leader_id?: string | null;
            members: components["schemas"]["TeamMemberView"][];
            name?: string | null;
            notified_at?: string | null;
            resource_ids: string[];
            unit_id: string;
            /** Format: int64 */
            version: number;
            work_item_ids: string[];
        };
        UnitRef: {
            id: string;
            name: string;
        };
        UnitView: {
            id: string;
            name: string;
            timezone: string;
        };
        WordView: {
            plural: string;
            singular: string;
        };
        WorkItemCreateBody: {
            billing_status?: string | null;
            category_id?: string | null;
            customer_name?: string | null;
            customer_ref?: string | null;
            date: string;
            description?: string | null;
            end_time?: string | null;
            /** Format: int64 */
            people_needed?: number | null;
            /** Format: int64 */
            resources_needed?: number | null;
            start_time?: string | null;
            status?: string | null;
            title: string;
            unit_id: string;
        };
        WorkItemCrew: {
            attributes: Record<string, never>;
            category_id?: string | null;
            /** @description The name to ask for at the door; no links into the customer register. */
            customer_name?: string | null;
            date: string;
            description?: string | null;
            end_time?: string | null;
            id: string;
            /** Format: int64 */
            people_needed?: number | null;
            /** Format: int64 */
            ref: number;
            /** Format: int64 */
            resources_needed?: number | null;
            start_time?: string | null;
            status: string;
            title: string;
            unit_id: string;
            updated_at: string;
            /** Format: int64 */
            version: number;
        };
        WorkItemFull: {
            attributes: Record<string, never>;
            billing_status: string;
            category_id?: string | null;
            created_at: string;
            created_by?: string | null;
            customer_contact_id?: string | null;
            customer_name?: string | null;
            customer_notified_at?: string | null;
            customer_organization_id?: string | null;
            customer_ref?: string | null;
            date: string;
            description?: string | null;
            end_time?: string | null;
            external_id?: string | null;
            external_source?: string | null;
            id: string;
            /** Format: int64 */
            people_needed?: number | null;
            /** Format: int64 */
            ref: number;
            /** Format: int64 */
            resources_needed?: number | null;
            start_time?: string | null;
            status: string;
            title: string;
            unit_id: string;
            updated_at: string;
            updated_by?: string | null;
            /** Format: int64 */
            version: number;
        };
        WorkItemView: components["schemas"]["WorkItemFull"] | components["schemas"]["WorkItemCrew"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issuer and client id for PKCE sign-in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfigView"];
                };
            };
            /** @description Missing or wrong x-publishable-key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sign-in is not configured on this server */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vocabulary, categories and attribute JSON Schemas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
        };
    };
    health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up and the database answers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The database did not answer */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in person, their units and what they may do */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeView"];
                };
            };
            /** @description No valid sign-in token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Signed in, but not linked to an active person */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    people_list: {
        parameters: {
            query?: {
                unit_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description People you may see; fields depend on your role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonView"][];
                };
            };
        };
    };
    teams_list: {
        parameters: {
            query: {
                unit_id: string;
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One office's teams for a day, with members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamView"][];
                };
            };
        };
    };
    teams_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreateBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamView"];
                };
            };
            /** @description Signed in, but not admin, manager or planner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One team */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamView"];
                };
            };
            /** @description Not found, or not visible to you */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    teams_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberBody"];
            };
        };
        responses: {
            /** @description Added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamView"];
                };
            };
            /** @description Signed in, but not admin, manager or planner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description constraint (e.g. already on another team that day) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    teams_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id */
                id: string;
                /** @description Person id */
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamView"];
                };
            };
            /** @description Signed in, but not admin, manager or planner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    units_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Your offices (admins: all) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitView"][];
                };
            };
        };
    };
    workItems_list: {
        parameters: {
            query: {
                unit_id: string;
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One office's jobs for a day */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemView"][];
                };
            };
        };
    };
    workItems_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkItemCreateBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemView"];
                };
            };
            /** @description Signed in, but not admin or manager */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workItems_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work item id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemView"];
                };
            };
            /** @description Not found, or not visible to you */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workItems_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work item id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchBody"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemView"];
                };
            };
            /** @description Not found, or not visible to you */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description conflict (stale version) or constraint (a rule) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
